import { MedusaContainer } from "@medusajs/framework"
import {
  ContainerRegistrationKeys,
  ModuleRegistrationName,
  Modules,
  ProductStatus,
} from "@medusajs/framework/utils"
import {
  createApiKeysWorkflow,
  createInventoryLevelsWorkflow,
  createProductCategoriesWorkflow,
  createProductsWorkflow,
  createRegionsWorkflow,
  createSalesChannelsWorkflow,
  createShippingOptionsWorkflow,
  createStockLocationsWorkflow,
  createStoresWorkflow,
  createTaxRegionsWorkflow,
  linkSalesChannelsToApiKeyWorkflow,
  linkSalesChannelsToStockLocationWorkflow,
} from "@medusajs/medusa/core-flows"
import {
  assertCard140SandboxEnv,
  verifyCard140Runtime,
} from "../local-sandbox/preflight"
import {
  CARD140_CATEGORIES,
  CARD140_COUNTRY_CODE,
  CARD140_CURRENCY_CODE,
  CARD140_PRODUCTS,
  CARD140_STOCKED_QUANTITY,
  STOREFRONT_REGION_ID,
  assertStorefrontContract,
} from "../local-sandbox/storefront-contract"

// This assertion runs as soon as Medusa imports the script. medusa-config.ts
// repeats it before any database connection whenever the sandbox marker exists.
assertCard140SandboxEnv(process.env)
assertStorefrontContract()

/**
 * Medusa's `Create*DTO` types omit `id`, but the DML id property is generated by
 * a `@BeforeCreate`/`@OnInit` hook calling `generateEntityId(this.id, prefix)`,
 * which keeps any value already present. Supplying the id is therefore the
 * supported way to make this fixture deterministic — no raw SQL, no data
 * rewrite, and the workflow rollback still deletes by the same id.
 */
const withPinnedId = <T extends object>(id: string, data: T): T =>
  ({ ...data, id }) as T

export default async function card140LocalFixture({
  container,
}: {
  container: MedusaContainer
}) {
  await verifyCard140Runtime(process.env)

  const logger = container.resolve(ContainerRegistrationKeys.LOGGER)
  const link = container.resolve(ContainerRegistrationKeys.LINK)
  const query = container.resolve(ContainerRegistrationKeys.QUERY)
  const fulfillment = container.resolve(ModuleRegistrationName.FULFILLMENT)

  for (const entity of [
    "product",
    "product_category",
    "region",
    "stock_location",
    "sales_channel",
  ]) {
    const { data } = await query.graph({ entity, fields: ["id"] })
    if (data.length) {
      throw new Error(
        `Expected an empty disposable database, but ${entity} already contains data; ` +
          "run npm run local:down and recreate it"
      )
    }
  }

  logger.info("Creating the isolated Card 140 BRL/Brazil fixture...")

  const {
    result: [salesChannel],
  } = await createSalesChannelsWorkflow(container).run({
    input: {
      salesChannelsData: [
        {
          name: "Card 140 Local Sales Channel",
          description: "Disposable local-only fixture",
        },
      ],
    },
  })

  const {
    result: [apiKey],
  } = await createApiKeysWorkflow(container).run({
    input: {
      api_keys: [
        {
          title: "Card 140 Local Publishable Key",
          type: "publishable",
          created_by: "",
        },
      ],
    },
  })
  await linkSalesChannelsToApiKeyWorkflow(container).run({
    input: { id: apiKey.id, add: [salesChannel.id] },
  })

  await createStoresWorkflow(container).run({
    input: {
      stores: [
        {
          name: "Card 140 Local Store",
          supported_currencies: [{ currency_code: "brl", is_default: true }],
          default_sales_channel_id: salesChannel.id,
        },
      ],
    },
  })

  const {
    result: [region],
  } = await createRegionsWorkflow(container).run({
    input: {
      regions: [
        withPinnedId(STOREFRONT_REGION_ID, {
          name: "Card 140 Brazil",
          currency_code: CARD140_CURRENCY_CODE,
          countries: [CARD140_COUNTRY_CODE],
          // Mercado Pago is intentionally not registered or selected here.
          payment_providers: ["pp_system_default"],
        }),
      ],
    },
  })
  if (region.id !== STOREFRONT_REGION_ID) {
    throw new Error(
      `Expected the storefront region id ${STOREFRONT_REGION_ID}, but Medusa created ${region.id}`
    )
  }

  await createTaxRegionsWorkflow(container).run({
    input: [{ country_code: CARD140_COUNTRY_CODE, provider_id: "tp_system" }],
  })

  const { result: categories } = await createProductCategoriesWorkflow(
    container
  ).run({
    input: {
      product_categories: CARD140_CATEGORIES.map((category) =>
        withPinnedId(category.id, {
          name: category.name,
          handle: category.handle,
          // Both default to false in the model, and the store API filters on
          // `is_active: true, is_internal: false`; an inactive category would
          // leave the storefront navigation empty despite matching ids.
          is_active: true,
          is_internal: false,
        })
      ),
    },
  })

  const categoryIdByKey = new Map(
    CARD140_CATEGORIES.map((category) => [category.key, category.id])
  )
  for (const category of CARD140_CATEGORIES) {
    if (!categories.some((created) => created.id === category.id)) {
      throw new Error(
        `Expected the storefront category id ${category.id} for ${category.key}, but Medusa assigned a different one`
      )
    }
  }

  const {
    result: [stockLocation],
  } = await createStockLocationsWorkflow(container).run({
    input: {
      locations: [
        {
          name: "Card 140 Local Warehouse",
          address: {
            city: "Sao Paulo",
            province: "SP",
            postal_code: "01001000",
            country_code: "BR",
            address_1: "Local fixture only",
          },
        },
      ],
    },
  })

  await link.create({
    [Modules.STOCK_LOCATION]: { stock_location_id: stockLocation.id },
    [Modules.FULFILLMENT]: { fulfillment_provider_id: "manual_manual" },
  })

  const { data: shippingProfiles } = await query.graph({
    entity: "shipping_profile",
    fields: ["id"],
  })
  if (shippingProfiles.length !== 1) {
    throw new Error("Expected exactly one default shipping profile in the disposable database")
  }
  const shippingProfile = shippingProfiles[0]

  const fulfillmentSet = await fulfillment.createFulfillmentSets({
    name: "Card 140 Brazil delivery",
    type: "shipping",
    service_zones: [
      {
        name: "Card 140 Brazil",
        geo_zones: [{ country_code: "br", type: "country" }],
      },
    ],
  })
  await link.create({
    [Modules.STOCK_LOCATION]: { stock_location_id: stockLocation.id },
    [Modules.FULFILLMENT]: { fulfillment_set_id: fulfillmentSet.id },
  })

  await createShippingOptionsWorkflow(container).run({
    input: [
      {
        name: "Card 140 Test Shipping",
        price_type: "flat",
        provider_id: "manual_manual",
        service_zone_id: fulfillmentSet.service_zones[0].id,
        shipping_profile_id: shippingProfile.id,
        type: {
          label: "Local test shipping",
          description: "No external carrier API is called",
          code: "card140-local",
        },
        prices: [{ currency_code: "brl", amount: 15 }],
        rules: [
          { attribute: "enabled_in_store", value: "true", operator: "eq" },
          { attribute: "is_return", value: "false", operator: "eq" },
        ],
      },
    ],
  })

  await linkSalesChannelsToStockLocationWorkflow(container).run({
    input: { id: stockLocation.id, add: [salesChannel.id] },
  })

  await createProductsWorkflow(container).run({
    input: {
      products: CARD140_PRODUCTS.map((product) => ({
        title: product.title,
        handle: product.handle,
        description: "Disposable product without remote images or external integrations",
        status: ProductStatus.PUBLISHED,
        shipping_profile_id: shippingProfile.id,
        category_ids: [categoryIdByKey.get(product.categoryKey)!],
        options: [{ title: "Variant", values: ["Local"] }],
        variants: [
          {
            title: "Local",
            sku: product.sku,
            manage_inventory: true,
            options: { Variant: "Local" },
            prices: [
              { currency_code: CARD140_CURRENCY_CODE, amount: product.amount },
            ],
          },
        ],
        sales_channels: [{ id: salesChannel.id }],
      })),
    },
  })

  const { data: inventoryItems } = await query.graph({
    entity: "inventory_item",
    fields: ["id", "sku"],
  })
  const inventoryItemBySku = new Map(
    inventoryItems.map((item) => [item.sku, item.id])
  )

  await createInventoryLevelsWorkflow(container).run({
    input: {
      inventory_levels: CARD140_PRODUCTS.map((product) => {
        const inventoryItemId = inventoryItemBySku.get(product.sku)
        if (!inventoryItemId) {
          throw new Error(`Expected a Card 140 inventory item for SKU ${product.sku}`)
        }
        return {
          location_id: stockLocation.id,
          stocked_quantity: CARD140_STOCKED_QUANTITY,
          inventory_item_id: inventoryItemId,
        }
      }),
    },
  })

  logger.info(
    `Card 140 fixture ready: BRL/BR region ${STOREFRONT_REGION_ID}, ` +
      `${CARD140_CATEGORIES.length} storefront categories, ${CARD140_PRODUCTS.length} local products, ` +
      `stock ${CARD140_STOCKED_QUANTITY} each, manual test shipping; no order or payment created`
  )
}
